/*
 * generated by Xtext
 */
package org.polarsys.kitalpha.ad.af.dsl.cs.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.polarsys.kitalpha.ad.af.dsl.cs.text.services.AfdescGrammarAccess;

public class AfdescParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AfdescGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.polarsys.kitalpha.ad.af.dsl.cs.text.parser.antlr.internal.InternalAfdescParser createParser(XtextTokenStream stream) {
		return new org.polarsys.kitalpha.ad.af.dsl.cs.text.parser.antlr.internal.InternalAfdescParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "NamedElement";
	}
	
	public AfdescGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AfdescGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
